import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/nextAuthProvider";
import NextThemeProvider from "@/providers/themeProvider";
import Globalstate from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextThemeProvider>
          <NextAuthProvider>
            {<Globalstate>
              {children}
            </Globalstate>}
          </NextAuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
